### ISSUE TITLE
Could you update the iOS 15.3 version? 

### ISSUE THREAD

**Issue by iiiyu** [pdso/DeveloperDiskImage#3]
Hi @pdso 
Hope you and your family stay safe.
There is a very useful project. But my phone is iOS 15.3.1 version now.
Could you update the iOS 15.3 DiskImage? 

Thank you very much.

**Comment by pdso** [comment]
Hello,
  There is no new versions from Apple.
You can use 15.2 diskImage for the iOS 15.3 instead.

**Comment by fxph35** [comment]
> Hi @pdso Hope you and your family stay safe. There is a very useful project. But my phone is iOS 15.3.1 version now. Could you update the iOS 15.3 DiskImage?
> 
> Thank you very much.

Hello,
There is no new versions from Apple.
You can use 15.2 diskImage for the iOS 15.3 instead.

**Comment by iiiyu** [comment]
> > Hi @pdso Hope you and your family stay safe. There is a very useful project. But my phone is iOS 15.3.1 version now. Could you update the iOS 15.3 DiskImage?
> > Thank you very much.
> 
> Hello, There is no new versions from Apple. You can use 15.2 diskImage for the iOS 15.3 instead.

OK, Thanks for your reply.
